### ISSUE TITLE
Issue when extracting maps when you havent enUS locale

### ISSUE THREAD

**Issue by LuigiElleBalotta** [CypherCore/Tools#2]
Please update the ExtractMaps(uint build) method (inside program.cs) with this:

http://luigiellebalotta.altervista.org/privatebin/?e67b09054b994c40#t+QNLBrwf13T3gOfk+roNWObz51u505bUIVpKuSUC/Y=

since the stream will be null if you use a client that doesn't have enUS locale (that is the default param of the function ReadFile() ).

Now it takes the first locale it find and use that for map extraction.

**Comment by hondacrx** [comment]
should be fixed in a273a8847786cb568ef072fb6cdecbc046da0661
PLease let me know

**Comment by LuigiElleBalotta** [comment]
fixed :)
