### ISSUE TITLE
Support for classic?

### ISSUE THREAD

**Issue by jjbrunton** [CypherCore/Tools#7]
Is there any possibility of support for classic? I'm assuming it would need to be expanded to read using WDBC2Reader?

**Comment by MaxtorCoder** [comment]
It's not just changing the db2 reader. It's opcodes and a lot of different things.

**Comment by jjbrunton** [comment]
> It's not just changing the db2 reader. It's opcodes and a lot of different things.

Cheers for the response.

Would you be able to expand on the 'lots of different things', I'm keen to have a go at updating it if possible.

**Comment by MaxtorCoder** [comment]
> > It's not just changing the db2 reader. It's opcodes and a lot of different things.
> 
> Cheers for the response.
> 
> Would you be able to expand on the 'lots of different things', I'm keen to have a go at updating it if possible.

If you have reverse engineering experience and know how to reverse WoW you don't really need me to expand on "a lot of different" things. 
But some of those are:
- Opcodes
- Packet Structures
- UpdateFields
- A lot more

**Comment by jjbrunton** [comment]
I got this working via DBCD in the end.

Thanks for the insight.

**Comment by MaxtorCoder** [comment]
> I got this working via DBCD in the end.
> 
> Thanks for the insight.

DBCD has almost all WoW versions supported that had DB2, so yeah. 😄
